-- ===================================================================
-- Table for Caching AI Responses
-- ===================================================================

create table if not exists public.response_cache (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb not null,
  expires_at timestamptz not null
);

-- Index for fast lookups by key
create index if not exists response_cache_key_idx on public.response_cache (key);

-- Index for efficient cleanup of expired entries
create index if not exists response_cache_expires_at_idx on public.response_cache (expires_at);

-- Enable RLS
alter table public.response_cache enable row level security;

-- Create a policy that allows the service role to manage the cache
-- This is more secure than granting public access.
create policy "Service role can manage response cache."
on public.response_cache
for all
to service_role
using (true)
with check (true);

-- Optional: Create a function to periodically clean up expired entries
create or replace function public.cleanup_expired_cache()
returns void
language plpgsql
as $$
begin
  delete from public.response_cache where expires_at < now();
end;
$$;
