-- ===================================================================
-- Table for User Strain Journals
-- ===================================================================

create table if not exists public.strain_journals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  strain_id text not null, -- The strain being reviewed
  rating integer check (rating >= 1 and rating <= 5), -- A 1-5 star rating
  dosage text, -- e.g., "2 puffs", "1g edible"
  effects text[], -- An array of effect tags, e.g., ['Relaxed', 'Creative', 'Euphoric']
  notes text, -- A free-text field for detailed thoughts
  activity_tags text[], -- e.g., ['Gaming', 'Watching Movie', 'Hiking']
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table public.strain_journals enable row level security;

-- Users can only view their own journals
drop policy if exists "Users can view own journals." on public.strain_journals;
create policy "Users can view own journals."
on public.strain_journals
for select
using (auth.uid() = user_id);

-- Users can insert their own journals
drop policy if exists "Users can insert own journals." on public.strain_journals;
create policy "Users can insert own journals."
on public.strain_journals
for insert
with check (auth.uid() = user_id);

-- Users can update their own journals
drop policy if exists "Users can update own journals." on public.strain_journals;
create policy "Users can update own journals."
on public.strain_journals
for update
using (auth.uid() = user_id);

-- Users can delete their own journals
drop policy if exists "Users can delete own journals." on public.strain_journals;
create policy "Users can delete own journals."
on public.strain_journals
for delete
using (auth.uid() = user_id);

-- Index for fast lookups
create index on public.strain_journals (user_id, created_at desc);
