-- ===================================================================
-- Table for User Feedback on Strains
-- ===================================================================

create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  strain_id text not null, -- Assuming strain_id is a string, adjust if it's an int
  rating integer check (rating >= -1 and rating <= 1), -- -1: thumbs-down, 0: viewed, 1: thumbs-up
  feedback_source text not null check (feedback_source in ('view', 'click', 'explicit_rating')),
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.user_feedback enable row level security;

-- Users can only see their own feedback
drop policy if exists "Users can view own feedback." on public.user_feedback;
create policy "Users can view own feedback."
on public.user_feedback
for select
using (auth.uid() = user_id);

-- Users can insert their own feedback
drop policy if exists "Users can insert own feedback." on public.user_feedback;
create policy "Users can insert own feedback."
on public.user_feedback
for insert
with check (auth.uid() = user_id);

-- Index for fast lookups
create index on public.user_feedback (user_id, strain_id);
