import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

self.skipWaiting();
clientsClaim();

// 1. Precache assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// 2. Runtime Caching for API (Optional, but let's keep it simple for now)
// We rely on the browser's fetch for API calls, or add Workbox routes here if needed.

self.addEventListener('fetch', (event) => {
    // Custom logic if needed, otherwise Workbox handles precached assets
});

// Background Sync (Future Implementation)
self.addEventListener('sync', (event) => {
    if (event.tag === 'sync-strain-reviews') {
        console.log('[ServiceWorker] Background Syncing Reviews...');
    }
});


